print("Bienvenido al directorio de notas")
print("Ingrese la nota 1")
nota1 = float(input())
print("Ingrese la nota 2")
nota2 = float(input())
print("Ingrese la nota 3")
nota3 = float(input())
prom = float((nota1+nota2+nota3)/3)
print("El estudiante obtuvo una nota final de ", prom)